# Generated by Django 4.0.4 on 2022-08-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(1, 'Entrada'), (2, 'Saída')], max_length=1)),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('dt_lancamento', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Caixa',
            },
        ),
    ]
