# Generated by Django 4.0.4 on 2023-01-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa',
            old_name='id_pessoa',
            new_name='id_pessoa_id',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='dt_lancamento',
            field=models.DateField(max_length=10),
        ),
    ]
