# Generated by Django 4.0.4 on 2022-08-18 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_curso', models.CharField(max_length=50, unique=True)),
                ('carga_horaria', models.DecimalField(decimal_places=0, default=1, max_digits=3)),
                ('vl_curso', models.DecimalField(decimal_places=3, default=1.0, max_digits=5)),
            ],
            options={
                'db_table': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('qtd_dias', models.DecimalField(decimal_places=0, max_digits=3)),
                ('qtd_horas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('periodo', models.IntegerField(choices=[(1, 'Matutino'), (2, 'Verpertino'), (3, 'Noturno')])),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cursos.cursos')),
            ],
            options={
                'db_table': 'Matriculas',
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_sala', models.CharField(max_length=50, unique=True)),
                ('capacidade', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nota_2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nota_3', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nota_4', models.DecimalField(decimal_places=2, max_digits=3)),
                ('media', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cursos.matriculas')),
            ],
            options={
                'db_table': 'Notas',
            },
        ),
    ]
