# Generated by Django 4.0.4 on 2022-08-18 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculas',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='id_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cursos.salas'),
        ),
    ]
